version: '3.5'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=postgres
    entrypoint: ["mix", "phx.server"]
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: therush_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432

volumes:
  db:
