version: '3.5'

services:
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: therush_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432

volumes:
  db:
